name: industrial_ci

on: push

jobs:
  industrial_ci:
    name: ROS ${{ matrix.ROS_DISTRO }} (${{ matrix.ROS_REPO }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ROS_DISTRO:
          - humble
          - jazzy
          - kilted
          - rolling
        ROS_REPO:
          - main
    steps:
      - uses: actions/checkout@v3
      - uses: ros-industrial/industrial_ci@master
        with:
          config: ${{ toJSON(matrix) }}
        env:
          NOT_TEST_BUILD: true
          UPSTREAM_WORKSPACE: ".repos -perception_interfaces/perception_msgs_rendering -perception_interfaces/perception_msgs_rviz_plugins -planning_interfaces/route_planning_msgs_rviz_plugins -planning_interfaces/trajectory_planning_msgs_rviz_plugins"
